#!/usr/bin/env node
/*-----------------------------------------------------*/
require('dotenv').config();
const http = require('http');
const port = process.env.SERVER_PORT || 8000;
/*-----------------------------------------------------*/

const server = new http.Server();
server.listen(port, () => console.info('Server initialized.'))
      .on('error', (err) => {

        if(err.syscall !== 'listen') throw err;
        const bind = (typeof port === 'string') ? `Pipe ${port}` : `Port ${port}`;
        /********* handle specific listen errors with friendly messages *********/
        switch(err.code){
          case 'EACCES':
            console.error(`${bind} requires elevated privileges.`);
            break;
          case 'EADDRINUSE':
            console.error(`${bind} is already in use.`);
            break;
          default:
            throw err;
        }
        process.exit(1);
      })
      .on('listening', () => {

        const addr = server.address();
        const bind = (typeof addr === 'string') ? `pipe ${addr}` : `port ${addr.port}`;
        console.info(`Listening on ${bind}.`);
      });